### ISSUE TITLE
Native module cannot be null

### ISSUE THREAD

**Issue by irondsd** [smekalka/react-native-universal-pedometer#3]
After installing it with yard add and linking through react-native link. It still works fine on android. If I comment import Pedometer from 'react-native-universal-pedometer', it loads, and if I uncomment it, it throws an error Native module cannot be null. I tried reinstalling it, didn't work.

**Comment by Lokeshcrowbotics** [comment]
> After installing it with yard add and linking through react-native link. It still works fine on android. If I comment import Pedometer from 'react-native-universal-pedometer', it loads, and if I uncomment it, it throws an error Native module cannot be null. I tried reinstalling it, didn't work.

What is the fix for this issue?
